os:
  - linux
env:
- LOGSENE_TOKEN=test-token
sudo: false
language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"
install:
  - mkdir tmp
  - mkdir test-token
  - npm i 
